# Base configs
baseurl: "https://iparaj.github.io/photos"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photos by iParaj"
subtitle: ""
author: "iParaj"
header:
 title: "iParaj"
 subtitle: "by Paraj Ganchaudhuri"
footer:
 name: ""
 bio: "Arriving Somewhere But Not [H]ere"
 github: "Want a website like this for yourself for free? Just <a href=\"https://github.com/iparaj\">fork this repo on github</a> ;)"
web_design: "iParaj"
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  twitter: "https://www.twitter.com/gparaj"
  instagram: "https://www.instagram.com/iparaj"
  dribbble: ""
  linkedin: "https://in.linkedin.com/in/iparaj"
  github: "https://www.github.com/iparaj"
